version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - {{cookiecutter.port}}:80

  redis:
    image: redis
    volumes:
      - "redis:/data"
    ports:
      - 6379:6379

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: {{cookiecutter.postgres_user}}
      POSTGRES_PASSWORD: {{cookiecutter.postgres_password}}
      POSTGRES_DB: {{cookiecutter.postgres_database}}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: {{cookiecutter.pgadmin_user}}
      PGADMIN_DEFAULT_PASSWORD: {{cookiecutter.pgadmin_password}}
      PGADMIN_LISTEN_PORT: {{cookiecutter.pgadmin_port}}
    depends_on:
      - postgres
    ports:
      - "5050:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:15672"

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery worker -A app.tasks --loglevel=DEBUG -c 1

  flower:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery flower --broker=amqp://{{cookiecutter.rabbitmq_user}}:{{cookiecutter.rabbitmq_password}}@rabbit:{{cookiecutter.rabbitmq_port}} --broker_api=http://{{cookiecutter.rabbitmq_user}}:{{cookiecutter.rabbitmq_password}}@rabbit:{{cookiecutter.rabbitmq_admin_port}}/api/ --port=5555
    ports:
        - 5555:5555
    depends_on:
      - "redis"
      - "rabbit"
      - "worker"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://{{cookiecutter.postgres_user}}:{{cookiecutter.postgres_password}}@postgres:5432/{{cookiecutter.postgres_database}}'
    depends_on:
      - "postgres"


volumes:
  db-data:
  pgadmin:
  redis: